import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { MercuriusDriverConfig, MercuriusDriver } from '@nestjs/mercurius';
import path = require('path');
import { CoreModule } from '../core/core.module';
import { PrismaModule } from '../prisma/prisma.module';
import { UsersModule } from '../users/users.module';

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql')
    }),
    CoreModule,
    UsersModule,
    PrismaModule
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}
